### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by fvirdia** [peerdavid/remapy#2]
I've currently been unable to log into my own account, regardless of how I input a fresh code. I believe it may be due to having some corrupted files on the cloud (the console returns me some
```
(Warning) No parent for item 3a616606-f9ba-4351-ab81-a2c37e30d025
```
errors.

**Comment by peerdavid** [comment]
What happens after you get this warning? Is the "File Explorer" Tab enabled? Because it seems that the login (backend) succeeded i.e. you got a user and device token, otherwise the file tree can not be downloaded.

Yes it seems that some files are corrupted, but nevertheless the login should not fail. I also had som e corrupted files and those should be displayed at the root level of the tree...

**Comment by fvirdia** [comment]
After clicking "sign in" and waiting until the remarkable website says "success", the status label remains as "could not sign in" and the file explorer tab stays disabled.

I'm happy to add some logging wherever the logging procedure is. Where should I look at?

**Comment by peerdavid** [comment]
Thank you very much,

I published something new, can you try this? If it still fails it would be interesting to debug the sign_in_event_handler in the gui/remarkable.py file...

**Comment by peerdavid** [comment]
> After clicking "sign in" and waiting until the remarkable website says "success", the status label remains as "could not sign in" and the file explorer tab stays disabled.
> 
> I'm happy to add some logging wherever the logging procedure is. Where should I look at?

Thank you very much,

I published something new, can you try this? If it still fails it would be interesting to debug the sign_in_event_handler in the gui/remarkable.py file...

**Comment by fvirdia** [comment]
It worked. The client did not ask to sign in again, and instead just opened the file tree.
The log was 
```bash
(env) :) fernando@fernando-dell ~/shared/remapy master $ ./rema.py 
(Warning) No parent for item 3a616606-f9ba-4351-ab81-a2c37e30d025
(Warning) Failed to publish subscriber.
year 0 is out of range
[Errno 2] No such file or directory: 'evince': 'evince'
```

Removing the line that calls evince (leaving xdg-open to do the lifting) solved the issue with file opening (I'm on KDE). Annotations look pretty good.

**Comment by peerdavid** [comment]
> It worked. The client did not ask to sign in again, and instead just opened the file tree. The log was [...]
Ah great thx for your help, but it seems that you have some corrupt files... 

> Removing the line that calls evince (leaving xdg-open to do the lifting) solved the issue with file opening (I'm on KDE). Annotations look pretty good.
I switched from xdg-open to evience because I can use the page parameter there i.e. the reader opens the same page that is also opened on the tablet which is super useful for me :)

Probably it would be nice to check if evience is installed and if not switch to xdg-open or so. But I will rework on this when I test it for windows.
