### ISSUE TITLE
[Windows] Pdf dosen't show the template lines

### ISSUE THREAD

**Issue by acujl** [peerdavid/remapy#23]
Hello there!

If I open a notebook in remapy where I have some lines as a template on the rM they dosen't show up, only what I write shows having white as background.

I've also added a path to a folder that has the templates on my tablet in the config section

**Comment by peerdavid** [comment]
Whenever you updated the template path all downloaded files must be rendered again, otherwise, the change is not visible (files are only rendered if something changed on the tablet side). To manually trigger a rendering again you can press "F5" for an individual document or by clicking the "ReSync" button all files are rendered again. 

Please also ensure that the provided path is accessible by remapy and contains all "P Week US.png", "P Week 2.png" files...
